### ISSUE TITLE
Maven central and/or jCenter sync

### ISSUE THREAD

**Issue by thoutbeckers** [PocketByte/kotlin-kydra-log#2]
We use this library in a project of ours, where it is imported by one of our own libraries.

It would be great if this the artifacts would be made available in maven central, or at the very least jCenter, so that dependent project don't have to specify the custom bintray repo.

This can be set up from the bintray console, e.g. see https://blog.bintray.com/2015/10/08/increase-your-maven-packages-exposure-by-adding-it-to-jcenter/

https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms

**Comment by KamiSempai** [comment]
I agree. But I have faced with one problem during publish into jCenter.

Here is the answer from Bintray Support:
> Thank you for your response,
> 
> In order to include a package in JCenter, the version under a valid package path should include a .pom file. a .jar/.aar file, a sources.jar file and optionally a javadoc.jar file . We won’t able to approve this request to include in JCenter with the Group ID as the required files are missing in versions of some of the package paths as mentioned below :
> 
> ru/pocketbyte/hydra/log/hydra-log-iosarm32/
> In the above package path, We can see that there are two paths, one used for the *.pom and* -sources.jar and *jar & optional *javoc files are missing.
> 
> ru/pocketbyte/hydra/log/hydra-log-iosarm64
> In the above package path, We can see that there are two paths, one used for the *.pom and* -sources.jar and *jar & optional *javoc files are missing.
> 
> ru/pocketbyte/hydra/log/hydra-log-iosx64/
> In the above package path, We can see that there are two paths, one used for the *.pom and* -sources.jar and *jar & optional *javoc files are missing.
> 
> ru/pocketbyte/hydra/log/hydra-log-macos/
> In the above package path, We can see that there are two paths, one used for the *.pom and* -sources.jar and *jar & optional *javoc files are missing.
> 
> Please update the versions with the required files so that we can verify your request.

I have already spoken with Kotlin developers. They know about this problem and tries to solve it.

**Comment by KamiSempai** [comment]
Maven Central - Done
