### ISSUE TITLE
iosSimulatorArm64 target support

### ISSUE THREAD

**Issue by carmelogallo** [PocketByte/kotlin-kydra-log#5]
Hi, 

during the migration of our library to the new `iosSimulatorArm64` target I was blocking because Kydra is not using it as well. Could you guys update it asap? 

Thanks

**Comment by carmelogallo** [comment]
Also I would like to know if this library is still supported because seems not at the moment.

**Comment by KamiSempai** [comment]
Target `iosSimulatorArm64` and other simulator targets are released under version 1.1.8.  
  
Library is supported, but for now I don't planning to implement a new features. Only bur fixes and updates like this.
